#!/bin/bash

format=$(cat input | tr '\n' ';' | sed 's/;;/\n/g' | sed 's/;/ /g')
nLines=$(printf "%s\n" "$format" | wc -l)
fields=("byr" "iyr" "eyr" "hgt" "hcl" "ecl" "pid" )
valid=0
checkRegex(){
	for j in ${!fields[@]}; do
		echo $1 | grep -E "${fields[$j]}:.+(\s|$)" > /dev/null || return 1
	done; return 0
}
for i in $(seq 1 $nLines); do 
	line=$(printf "$format" | sed -n "$i"p)
	checkRegex "$line" && let valid+=1
done
echo $valid
