#!/bin/bash

IFS=$'\n' read -rd '' -a inArray<<<$(cat input | sort -n)
oneCount=0; threeCount=1

if echo "${inArray[@]}" | grep -w -q "1"; then let oneCount+=1
elif echo "${inArray[@]}" | grep -w -q "3"; then let threeCount+=1; fi;

for i in ${!inArray[@]}; do
	if [ "$i" -gt 0 ]; then
		diff=$((${inArray[$i]} - ${inArray[$i - 1]}))
		case $diff in
			1) let oneCount+=1;;
			3) let threeCount+=1;;
		esac
	fi
done
echo $((oneCount * threeCount))
