#!/bin/bash

IFS=$'\n' read -rd '' -a numbers<<<$(cat input | sort -n)
inArray(){
	check="$1"
	if $(echo "${numbers[@]}" | grep -q -w "$check" &> /dev/null); then return 0 
	else return 1; fi;
}
oneChain=0
chains=()
nextNumber(){
	num=$1
	if $(inArray "$((num + 1))"); then 
		next=$((num + 1))
		let oneChain+=1
		nextNumber $next
	fi
	if $(inArray "$((num + 3))"); then
		next=$((num + 3))
		chains+=("$oneChain")
		oneChain=0
		nextNumber $next
	fi
}
nextNumber 0
count2=0; count3=0; count4=0
for i in ${!chains[@]}; do
	case ${chains[$i]} in
		2)let count2+=1;;
		3)let count3+=1;;
		4)let count4+=1;;
	esac
done
echo "(2 ^ $count2) * (4 ^ $count3) * (7 ^ $count4)"| bc
