#!/bin/bash

in=("shiny gold")

for i in ${!in[@]}; do
	line=$(grep "^${in[$i]}" input)
	if echo $line | grep "no other" > /dev/null; then
		echo dead end
	else
		IFS=$';' read -rd '' -a children<<<$(echo $line | sed -E 's/^.*contain (.*)\./\1/g; s/, /;/g')
		#printf "%s\n" "${children[@]}"
		#num=$(echo "${children[@]}" | sed 's/[^0-9]//g')
		num=0
		for j in ${!children[@]}; do
			let num+=$(echo ${children[$j]} | sed 's/[^0-9]//g')
			echo $num
		done
		#echo "1 2 3" | sed 's/ /+/g' | bc
		#total=
	fi
done

