#!/bin/bash
source ~/.bin/ansi-escape
level=1; count=0
loop(){
	in=("$@")
	unset search
	while [ ${#in[@]} -gt 0 ]; do
		let level+=1
		for i in ${!in[@]}; do
			line=$(grep -E "^${in[$i]}" input)
			if echo $line | grep "no other bags" > /dev/null; then 
				empty+=("${in[$i]}")
			else IFS=";" read -rd '' -a contents<<<$(echo $line | sed -E 's/^.*bags contain (.*)\.$/\1/g; s/, /;/g')
				for j in ${!contents[@]}; do
					bag=$(echo ${contents[$j]} | sed -E 's/^[0-9]* (.*) (bag|bags)$/\1/g')
					num=$(echo ${contents[$j]} | sed -E 's/[^0-9]//g')
					search+=("$bag")
					thislevel+=("$bag")
				done
			fi
		done
		loop "${search[@]}"
	done
}
#loopback(){
	#in=("$@")
	#printf "%s\n" "${thislevel[@]}" | sort | uniq
	#echo; echo
	#echo empty bags:
	#printf "%s\n" "${in[@]}"
#}
#search=("shiny gold")
#loop "${search[@]}"
#IFS=$'\n' read -rd '' -a empty<<<$(printf "%s\n" "${empty[@]}" | sort | uniq) 
##echo ${#empty[@]}
#loopback "${empty[@]}"
##for i in $(seq $level 1); do
	##echo returning from level $i
##done
