#!/bin/bash
source ~/.bin/ansi-escape
nLines=$(awk -F"\n" -v RS= '{print NF}' input)
search=("shiny gold")
count=0
for l in $(seq 1 $nLines); do searchLines+=("$l"); done

recurse(){
	in=("$@")
	printf "${red}There are ${#searchLines[@]} lines to search:\n\n${norm}"
	unset search
	for i in ${!in[@]}; do
		printf "%s\n" "${yell}Searching '${in[$i]}'${norm}"
		for j in ${!searchLines[@]}; do
			index=$((j + 1))
			#echo Searching line ${searchLines[$j]}
			#line=$(sed -n "$index"p testinput)
			line=$(sed -n "$index"p input)
			#echo $line
			echo $line | grep -E "^.*contain.*${in[$i]}" > /dev/null &&
				{ 
					#Finds a match
					printf "%s\n" "${bold}Match!${norm}" 
					#Add container to search
					container=$(echo $line | sed 's/ bags contain.*$//')
					search+=("$container")
					printf "$container added to search\n"
					printf "Line ${searchLines[$j]} removed from input\n"
					#Unset current line from search Lines
					#delete j from search lines
					unset searchLines[$j]
					let count+=1
					
				}
		done
	done
}

#for m in $(seq 1 10); do
m=1
while [ ${#search[@]} -gt 0 ]; do
	recurse "${search[@]}"
	echo Search $m >> searches
	printf "Search terms\n%s\n" "$(printf "%s\n" "${search[@]}")" >> searches
	printf "Number of search terms ${#search[@]}\n"
	printf "Search terms\n %s\n" "$(printf "%s\n" "${search[@]}")"
	#printf "Lines to search: %s\n" "$(printf "%s, " "${searchLines[@]}")"
	printf "Matches found: $count\n"
	let m+=1
done
