#!/bin/bash

xTot=$(($(sed -n 1p input | wc -m) - 1))
yTot=$(cat input | wc -l)
xArr=(1 3 5 7 1)
yArr=(1 1 1 1 2)
treeTot=1

for i in ${!xArr[@]}; do
	trees=0
	xPos=1; yPos=1
	xMove=${xArr[$i]}; yMove=${yArr[$i]}
	while [ "$yPos" -le "$yTot" ]; do
		let yPos+=$yMove
		line=$(sed -n "$yPos"p input)
		let xPos+=$xMove
		if [ "$xPos" -gt "$xTot" ] ; then xPos=$((xPos - xTot)); fi
		coord=${line:$((xPos - 1)):1}
		if [ "$coord" == "#" ]; then let trees+=1; fi
	done
	let treeTot*=$trees
done
echo $treeTot
