#!/bin/bash

IFS=$'\n' read -rd '' -a lines<<<$(cat input)
total=0
for i in ${!lines[@]}; do
	mass=$(((lines[$i] / 3) - 2))
	let total+=$mass
	while [ "$mass" -gt 0 ]; do
		mass=$(((mass / 3) - 2))
		if [ $mass -gt 0 ]; then let total+=$mass; fi
	done
done
echo $total
