#!/bin/bash

nLines=$(cat input | wc -l)
high=0; low=1000
codeToID(){
	row=0; col=0
	inBin=$(echo "$1" | sed -E 's/[FL]/0/g' | sed -E 's/[BR]/1/g' | sed -E 's/(0|1)/\1 /g')
	binRow=$(echo "$inBin" | sed -E 's/(0 |1 ){3}$//')
	binCol=$(echo "$inBin" | sed -E 's/^(0 |1 ){7}//')
	binRow=($binRow); binCol=($binCol)
	for i in ${!binRow[@]}; do
		a=$((${#binRow[*]} - i - 1))
		b=$((${binRow[$i]} * $(echo "2^$a" | bc)))
		let row+=$b
	done
	for i in ${!binCol[@]}; do
		a=$((${#binCol[*]} - i - 1))
		b=$((${binCol[$i]} * $(echo "2^$a" | bc)))
		let col+=$b
	done
	id=$((row * 8 + col))
}
for i in $(seq 1 $nLines); do
	code=$(sed -n "$i"p input)
	codeToID "$code"
	if [ $id -gt $high ]; then high="$id"; fi
	if [ $id -lt $low ]; then low="$id"; fi
done
echo $low
echo $high
